baseurl = "https://zenogries.com"
title = "Zeno Gries"
theme = "one-portfolio"
languageCode = "de"

# Enable Google Analytics by entering your tracking code
googleAnalytics = "UA-140792581-1"

[params]
  copyright = "&copy;2020 Zeno Gries"

  email     = "zenogries@gmail.com"

  # Nav links in the top menu
  [[params.navlinks]]
  name = "Arbeiten"
  url  = "portfolio/"

  [[params.navlinks]]
  name = "Kollektive Arbeiten"
  url  = "collective/"

  [[params.navlinks]]
  name = "About"
  url  = "about/"

  [params.social]
  # facebook  = "full page or profile url in facebook"
  # instagram = "full profile url in instagram"
  vimeo     = "https://vimeo.com/zenogries"
  github    = "https://github.com/papayapeter"
